"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.db = exports.pool = void 0;
var serverless_1 = require("@neondatabase/serverless");
var neon_serverless_1 = require("drizzle-orm/neon-serverless");
var ws_1 = require("ws");
var env_ts_1 = require("../env.ts");
serverless_1.neonConfig.webSocketConstructor = ws_1.default;
exports.pool = new serverless_1.Pool({ connectionString: env_ts_1.env.DATABASE_URL });
exports.db = (0, neon_serverless_1.drizzle)(exports.pool);
